### ISSUE TITLE
PA3

### ISSUE THREAD

**Issue by akimovatatiana** [GsG-bOIIZ/distributed-programming#1]
1. Необходимо заменить абсолютные пути к проектам на относительные в скриптах запуска:

https://github.com/GsG-bOIIZ/distributed-programming/blob/42533906cec3b9843f7623c7878b57eb9dfdb771/scripts/start.cmd#L6
https://github.com/GsG-bOIIZ/distributed-programming/blob/42533906cec3b9843f7623c7878b57eb9dfdb771/scripts/start.cmd#L9

2. rank считается только один раз при первом вводе в форме после запуска процессов, после второго ввода в форме процесс RankCalculator вылетает с исключением.

3. Не очень удачное решение - ссылаться на запускаемый проект как на библиотеку.
https://github.com/GsG-bOIIZ/distributed-programming/blob/42533906cec3b9843f7623c7878b57eb9dfdb771/RankCalculator/RankCalculator.csproj#L16
Либо вынесите общий код в отдельную библиотеку и подключите её из проектов Valuator и RankCalculator. Либо если вы хотите использовать только хост и порт для подключения к БД, заведите свои константы в проекте RankCalculator

**Comment by GsG-bOIIZ** [comment]
Поправил первое и третье замечания.

На счет второго не понимаю в чем проблема. У меня все корректно работает.

**Comment by akimovatatiana** [comment]
Может сработать некорректно, потому что вы сначала отправляете событие для расчета ранга с идентификатором текста:
https://github.com/GsG-bOIIZ/distributed-programming/blob/5ecdcfbc3652a8e9324e822b8f41767a87aaf5e8/Valuator/Pages/Index.cshtml.cs#L38
И только после этого записывайте текст с этим идентификатором в БД:
https://github.com/GsG-bOIIZ/distributed-programming/blob/5ecdcfbc3652a8e9324e822b8f41767a87aaf5e8/Valuator/Pages/Index.cshtml.cs#L47
То есть происходит такая ситуация, что текст не успевает записаться в БД, следовательно RankCalculator не может получить из БД соотвествующий текст и вылетает с ошибкой, что текст равен null при попытке работы с ним в методе CalculateRank.

**Comment by GsG-bOIIZ** [comment]
Исправил замечание

**Comment by akimovatatiana** [comment]
Необходимо исправить расчет Плагиата, сейчас он всегда равен 1, даже после отправки нового текста.

**Comment by GsG-bOIIZ** [comment]
Исправил
